services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-13.1.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./netsage-sankey-panel:/var/lib/grafana/plugins/netstage-sankey-panel
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
