// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  BlockComment = 2,
  Filter = 3,
  Not = 4,
  And = 5,
  Or = 6,
  Column = 7,
  Operator = 8,
  Value = 9,
  String = 10,
  Literal = 11,
  ValueLParen = 12,
  ListOfValues = 13,
  ValueComma = 14,
  ValueRParen = 15
